version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless package --stage dev
  post_build:
    commands:
      - serverless deploy --stage dev --region ap-southeast-2
artifacts:
  files:
    - .serverless/*
    - packaged-template.yaml