version: 0.3

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies and Serverless CLI..."
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm install
  build:
    commands:
      - echo "Verifying ZIP contents..."
      - sls deploy
  post_build:
    commands:
      - echo "Deployment completed successfully!"