version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies and Serverless CLI..."
      - npm install --production # 只安裝生產依賴
      - npm install -g serverless # 安裝 Serverless CLI
      - serverless --version # 驗證 Serverless 安裝
  build:
    commands:
      - echo "Building Lambda package..."
      - mkdir -p dist
      - cp -r node_modules dist/ # 複製依賴到 dist 資料夾
      - cp -r handlers/*.js dist/ # 複製 Lambda 函數檔案
      - cd dist
      - zip -r ../lambda-package.zip . # 打包為 .zip 檔案
  post_build:
    commands:
      - echo "Build completed, ready for deployment."

artifacts:
  files:
    - lambda-package.zip
  discard-paths: yes