version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies and Serverless CLI..."
      - node -v # 驗證 Node.js 版本
      - npm -v # 驗證 npm 版本
      - ping -c 4 registry.npmjs.org # 測試網路連線
      - npm install || { echo "npm install failed"; exit 1; } # 捕捉錯誤
      - npm install -g serverless # 安裝 Serverless CLI
      - serverless --version # 驗證 Serverless 安裝
  build:
    commands:
      - echo "Building Lambda package..."
      - mkdir -p dist
      - cp -r node_modules dist/ # 複製依賴到 dist 資料夾
      - cp -r handlers/*.js dist/ # 複製 Lambda 函數檔案
      - cp serverless.yml dist/ # 複製 serverless.yml
      - cd dist
      - zip -r ../lambda-package.zip . # 打包為 .zip 檔案
      - unzip -l ../lambda-package.zip # 調試：列出 .zip 內容
  post_build:
    commands:
      - echo "Build completed, ready for deployment."

artifacts:
  files:
    - lambda-package.zip
  discard-paths: yes