version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies and Serverless CLI..."
      - node -v
      - npm -v
      - ping -c 4 registry.npmjs.org
      - rm -rf node_modules
      - npm cache clean --force
      - npm install || { echo "npm install failed"; exit 1; }
      - npm install -g serverless@3.38.0
      - serverless --version
  build:
    commands:
      - echo "Building Lambda package..."
      - mkdir -p dist
      - cp -r node_modules dist/
      - cp confirmUpload.js dist/
      - cp uploadBanner.js dist/
      - cd dist
      - zip -r ../lambda-package.zip .
      - unzip -l ../lambda-package.zip
  post_build:
    commands:
      - echo "Verifying ZIP contents..."
      - unzip -l lambda-package.zip | grep "node_modules" || { echo "node_modules missing in ZIP"; exit 1; }
      - unzip -l lambda-package.zip | grep "confirmUpload.js" || { echo "confirmUpload.js missing in ZIP"; exit 1; }
      - unzip -l lambda-package.zip | grep "uploadBanner.js" || { echo "uploadBanner.js missing in ZIP"; exit 1; }
      - echo "Build completed, ready for deployment."

artifacts:
  files:
    - lambda-package.zip
    - serverless.yml
  discard-paths: yes